### ISSUE TITLE
Threshold based on object value

### ISSUE THREAD

**Issue by KonradHoeffner** [dice-group/LIMES-legacy#13]
Many geospatial enties have a Zipf's law distribution, for example cities and their populations and I guess mountains and their area and height. This makes determining the correct distance threshold difficult, as a city with millions of inhabitants should allow a higher maximum distance than a small village. I propose to add variable thresholds based on some object values, e.g. the population of a city (or the logarithm or something thereof).

**Comment by Kleanthi** [comment]
Link Specifications in LIMES abide particular rules regarding the threshold value. So the value can only range for [0,1]
