### ISSUE TITLE
Add function to compare relative difference of numbers

### ISSUE THREAD

**Issue by KonradHoeffner** [dice-group/LIMES-legacy#14]
I want to compare population numbers and the existing metrics like euclidean seem not suitable for this to me. I propose to add a simple function "relative", defined as:
a=0^b=0 -> return 1
a=0 XOR b=0 -> return 0
return min(a/b,b/a).

**Comment by FatemeSH** [comment]
can you help me and say how can I define a function in lines?
thanks

**Comment by FatemeSH** [comment]
could you solve your problem?

**Comment by Kleanthi** [comment]
Hello and sorry for the delayed answer.
Please use the new LIMES available at: https://github.com/dice-group/LIMES
We also have included a new developer manual that will answer your question: http://dice-group.github.io/LIMES/developer_manual/.
