### ISSUE TITLE
OneToOne execution generates n-to-n mapping

### ISSUE THREAD

**Issue by KonradHoeffner** [dice-group/LIMES-legacy#16]
I link LinkedGeoData countries to DBpedia countries but despite "<EXECUTION>OneToOne</EXECUTION>" LIMES produces an n-to-n mapping (excerpt):

http://linkedgeodata.org/triplify/node432425063 owl:sameAs http://dbpedia.org/resource/Republic_of_the_Congo .
http://linkedgeodata.org/triplify/node432425063 owl:sameAs http://dbpedia.org/resource/Democratic_Republic_of_the_Congo .
http://linkedgeodata.org/triplify/node435981993 owl:sameAs http://dbpedia.org/resource/Democratic_Republic_of_the_Congo .

**Comment by ngonga** [comment]
It simply means that these all have the same similarity. The hospital resident approach then returns all possible solutions. Will be improved in the upcoming version.
