### ISSUE TITLE
can't get links

### ISSUE THREAD

**Issue by dalgi** [dice-group/LIMES-legacy#21]
Hi
I'm new in LIMES.. I want to use LIMES for finding links in my RDF data.
but when I'm running that, it can't retrived entities and I got this in the console

 INFO [main](SparqlQueryModule.java:141) - Querying the endpoint.
 INFO [main](SparqlQueryModule.java:149) - Getting statements 0 to 1000
 INFO [main](SparqlQueryModule.java:248) - Retrieved 0 triples and 0 entities.
 INFO [main](SparqlQueryModule.java:249) - Retrieving statements took 0.312 seconds.
 INFO [main](HybridCache.java:179) - Serializing 0 objects to ...

But when I run the same sparql query in my sparql endpoint, it retrived entities. 
help me please.

**Comment by Kleanthi** [comment]
Hello and sorry for the delayed answer.
Please use the new LIMES available at: https://github.com/dice-group/LIMES
We also have included a new user manual that will answer your question: http://dice-group.github.io/LIMES/user_manual/.
