### ISSUE TITLE
replace function

### ISSUE THREAD

**Issue by dalgi** [dice-group/LIMES-legacy#24]
Hi
I want to use replace function in my code. But I don't know how it works and where I can use it.
I found it in user_manual page page 5...
             replace(String a,String b) for replacing each occurrence of a with b
please give me an example.

**Comment by Kleanthi** [comment]
Hello and sorry for the delayed answer.
Please use the new LIMES available at: https://github.com/dice-group/LIMES
We also have included a new user manual that will answer your question: http://dice-group.github.io/LIMES/user_manual/.
